service: rails_restaurant
image: aldosalasrdz/rails_restaurant
servers:
  web:
    - 5.161.179.211
proxy: false
registry:
  username: aldosalasrdz
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
  clear:
    DB_HOST: rails_restaurant-db
accessories:
  db:
    image: mysql:8.0
    host: 5.161.179.211
    port: "127.0.0.1:3306:3306"
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      # - config/mysql/production.cnf:/etc/mysql/my.cnf
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
